### ISSUE TITLE
[KUMap] Compile error when google map API used

### ISSUE THREAD

**Issue by jsonbsd** [jsonbsd/kuvid#14]
Hi, something wrong compiling codes google map API used.

```
Failed to compile.

./src/components/KUMap.js
Module not found: Can't resolve 'google-maps-react' in '/Users/ljy/Git/kuvid/src/components'
```

Is there any package to install additionally?

**Comment by kamakeyo** [comment]
npm install --save google-maps-react

**Comment by jsonbsd** [comment]
react 버전 14로 맞추고 project 경로 내에 google-maps-react 설치 시 해결됨
