### ISSUE TITLE
[Compile Error] CSS compile issue

### ISSUE THREAD

**Issue by jsonbsd** [jsonbsd/kuvid#27]
CSS resource cannot found
확인해보니 css 관련 파일들이 누락된 것 같은데 ignore된 것인지 확인 필요

```
Failed to compile.

./src/components/KUMap.js
Cannot find file: 'imageCss.css' does not match the corresponding name on disk: './src/components/css/imagecss.css'.
```

**Comment by juj7347** [comment]
이전거에 최신화 다 되어있을텐데 이상하네... 다시 머지 해보셈

**Comment by jsonbsd** [comment]
`./src/components/css/imagecss.css` 경로 지정이 잘못된 것 아닌가?

**Comment by jsonbsd** [comment]
`imagecss.css` 에서 `imageCss.css` 로 파일 이름 변경 필요

**Comment by kamakeyo** [comment]
아까 C 대문자인데 소문자로 오타 있었던 거 같은데 수정해봤나?
